spring:  application:    name: stock-serviceserver:  port: 8302

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://localhost:8300/eureka/
  instance:
    hostname: localhost