spring:
  application:
    name: db-service
server:
  port: 8301

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8300/eureka/
  instance:
    hostname: localhost