server:  port: 8300
eureka:  client:    register-with-eureka: false
    fetch-registry: false  server:    max-threads-for-peer-replication: 0    zuul:  prefix: /api  routes:    db-service:      path: /db-service/**      url: http://localhost:8301    stock-service:      path: /stock-service/**      url: http://localhost:8302